// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpT8JFcupnhbxKgQw0c0ONlISaCCsXy2E',
    appId: '1:773155766362:web:4b378c017e61d6f02e5863',
    messagingSenderId: '773155766362',
    projectId: 'house-rent-bc1fe',
    authDomain: 'house-rent-bc1fe.firebaseapp.com',
    databaseURL: 'https://house-rent-bc1fe-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'house-rent-bc1fe.appspot.com',
    measurementId: 'G-QENCVJQ1ZC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAv4aud2UX8oDcnS7sOnHWq6oIurmBMi4',
    appId: '1:773155766362:android:02a7ec665de8df0d2e5863',
    messagingSenderId: '773155766362',
    projectId: 'house-rent-bc1fe',
    databaseURL: 'https://house-rent-bc1fe-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'house-rent-bc1fe.appspot.com',
  );
}
